### ISSUE TITLE
can't delete note

### ISSUE THREAD

**Issue by nutpantz** [MartinXPN/ProCorrector---How-NOT-to-code-in-Android#1]
Just tried the spell checker and I like it
I love it's offline and the dictionary is customisable
But I can't figure out how to delete notes
I cleared data for the app to get rid of a bunch of test notes
I did.. But that is not very feasible is I want to use it to create
On a regular basis.

I would love it if this app could be found on fdroid also
Add I use that the update most of my open source software

**Comment by MartinXPN** [comment]
Dear user,

You can just swipe the item to the left and click on the "trash button".

Please see attached some screenshots that explain how to delete a document.

You can find the source-code on github. The link is in the "about" section of the app.

Thanks for feedback.
If you have any questions please don't hesitate to ask.

Best regards,
XPN Inc.

On Wed, Apr 20, 2016 at 8:47 PM, nutpantz < notifications@github.com [notifications@github.com] > wrote:
Just tried the spell checker and I like it
I love it's offline and the dictionary is customisable
But I can't figure out how to delete notes
I cleared data for the app to get rid of a bunch of test notes
I did.. But that is not very feasible is I want to use it to create
On a regular basis.

I would love it if this app could be found on fdroid also
Add I use that the update most of my open source software
